### PR TITLE
End to end rota integration

### PR DESCRIPTION
**Pull request by chriscarter90**
WIP - **DO NOT MERGE**.

### CODE REVIEW

**Comment by ansonK** [comment]
Generating a rota fails for me:
```
NoMethodError (undefined method `split' for nil:NilClass):
  lib/rota_generation/solution.rb:18:in `sanitize!'
  lib/rota_generation/solution.rb:8:in `clauses'
  lib/rota_generation/generator.rb:29:in `parse!'
  lib/rota_generation/generator.rb:12:in `generate_rota'
  app/controllers/procurement_area_rotas_controller.rb:17:in `create'
```

Looking at the constants supplied to the Rota it seems that a few are 0:
```
firm("c9df8774-62fa-4fa3-8a56-8eb302511f87").
firm("52bb0b94-04a7-47b3-a837-3727b1d4ec01").
firm("c9df8774-62fa-4fa3-8a56-8eb302511f87").
firm("96cf01b8-384b-4121-a012-cebf9fcf2d76").
firm("52bb0b94-04a7-47b3-a837-3727b1d4ec01").
firm("2531cb6d-ad14-43d0-bafb-7cdee607d3fc").

#const num_firms = 6.
#const num_shifts = 0.
#const num_days = 0.
#const num_slots = 0.

% warning: slots_per_shift_date/6 is never defined
% warning: date/4 is never defined
% warning: shift/1 is never defined
```

**Comment by chriscarter90** [comment]
I think this is ready to merge now, at long last. Would be good if someone could have another glace. @ansonK? @pixeltrix? @FriedSock? @novotnyjakub?

**Comment by ansonK** [comment]
Can we add a quick note in the readme about the debug env variable to print out the solver info please?

**Comment by ansonK** [comment]
lgtm otherwise

**Pull request merged**
