### PR TITLE
[RFC] Modify models usage of the api

### PR DESCRIPTION
**Pull request by pedrosmmoreira**
Starting to implement the first story that consumes data from the auth Api, I have ran into the following issue:
Given the client for the data api (residing in the auth app) requires a
valid user token to be instantiated, we can no longer rely on it being
fully initialized on app boot.
boot.

This addresses the issue by removing the inheritance structure
descending from ApiModel, so the client can be initialized with a fresh
user token per request.

Since the client returns full fledged models, this extracts a dedicated
finder and a presenter for each model, in this case `organisation`.

### CODE REVIEW

**Comment by ansonK** [comment]
> Given the client for the auth app requires a valid user token to be
> instantiated, we can no longer rely on it being fully initialized on app
> boot

This is not correct. The API client is instantiated for each *request* not on app boot as the API client requires an auth_token that can (currently) only be obtained on a per user basis from the session

**Comment by pedrosmmoreira** [comment]
Ah, slight miscommunication, sorry. This change intents to instantiate the client per request, at the controller level.
The way the service registry + ApiModel inheritance model was structured relied on instantiating the client in an initializer, which is what I propose to change.
I've also made the FakeDataApi accept a token, in order to maintain the same Api contract.

**Comment by ansonK** [comment]
Ok that sounds good then. So the FakeApi is solely for use in tests.
I would prefer to be able to declare what the API responds with from each request spec, rather than having a hard coded list that all request specs would need to use.
Something like giving ```DefenceRequestServiceRota.register_service``` a stub API client per request spec?

**Comment by pedrosmmoreira** [comment]
Yep, we can do that. Currently I've set it in a helper, I can extend it to take a param, something along the lines of `set_data_api_to :fake_organisation_data`. Is that along the lines that you were thinking?

**Comment by ansonK** [comment]
Yup that looks good to me thanks.
LGTM

**Pull request merged**
